<?php

namespace DataBaseBundle\Repository;

/**
 * MyOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
