<?php

namespace DataBaseBundle\Repository;

/**
 * ObtainedSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObtainedSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
