<?php

namespace DataBaseBundle\Repository;

/**
 * QuizSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSession(){
        $query = $this->_em->createQuery('SELECT a.creationDate,COUNT (a.creationDate) as nbre FROM DataBaseBundle:QuizSession a WHERE a.creationDate > (CURRENT_DATE()-10) GROUP BY a.creationDate');
        $result = $query->getResult();
        return $result;
    }
}
