<?php

namespace DataBaseBundle\Repository;

/**
 * QuizSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
